In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="5"
import tensorflow
import torch

from SDNET.model import SDNETmodel
from SDNET.CIT.model import CITModel

/mnt/sdd/fcastro/envs/TF/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/mnt/sdd/fcastro/envs/TF/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/mnt/sdd/fcastro/envs/TF/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/mnt/sdd/fcastro/envs/TF/lib/python3.6/site-packages/tensorflow/python/frame

In [2]:
segmentation_path = None
lambda_value = 0.05
epochs = 1
batch_size = 2
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


data_path = "../data/COVIDGR1.0reducido-cropped" 
csv_path = "../partitions/partition_reducido.csv"

#data_path = "../data/Revisadas-Clasificadas-Recortadas" 
#csv_path = "../partitions/partition_iid_1nodes_1.csv"

In [3]:
sdnet_model = SDNETmodel(lambda_value, epochs, batch_size, device)
cit_model = CITModel(['N', 'P'], "resnet18", lambda_value, batch_size, epochs, device)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [6]:
data, label, train_data, train_label, test_data, test_label, train_files, test_files = sdnet_model.get_data_csv(data_path, csv_path)
print(len(train_data))
print(len(train_label))

print(train_data)



16
16
[[[[ 86  86  86]
   [ 82  82  82]
   [ 75  75  75]
   ...
   [ 58  58  58]
   [ 58  58  58]
   [ 56  56  56]]

  [[ 92  92  92]
   [ 84  84  84]
   [ 77  77  77]
   ...
   [ 54  54  54]
   [ 58  58  58]
   [ 64  64  64]]

  [[ 99  99  99]
   [ 97  97  97]
   [ 87  87  87]
   ...
   [ 57  57  57]
   [ 56  56  56]
   [ 55  55  55]]

  ...

  [[164 164 164]
   [180 180 180]
   [180 180 180]
   ...
   [181 181 181]
   [181 181 181]
   [180 180 180]]

  [[177 177 177]
   [184 184 184]
   [191 191 191]
   ...
   [175 175 175]
   [171 171 171]
   [174 174 174]]

  [[171 171 171]
   [182 182 182]
   [178 178 178]
   ...
   [182 182 182]
   [178 178 178]
   [174 174 174]]]


 [[[101 101 101]
   [126 126 126]
   [128 128 128]
   ...
   [ 94  94  94]
   [ 94  94  94]
   [ 94  94  94]]

  [[136 136 136]
   [139 139 139]
   [144 144 144]
   ...
   [ 97  97  97]
   [ 97  97  97]
   [ 97  97  97]]

  [[137 137 137]
   [128 128 128]
   [130 130 130]
   ...
   [105 105 105]
   [102 102 102]
   [1

In [5]:
#sdnet_model.train_CIT(train_data, train_label)
#sdnet_model.train_Classifier(train_data, train_label)
cit_model.train(train_data, train_label)

  0%|          | 0/2 [00:00<?, ?it/s]

[INFO] weights = [1. 1.]


[Validating]: Acc_D: 1.0000:  50%|█████     | 1/2 [00:01<00:01,  1.12s/it]


RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 31.75 GiB total capacity; 1.42 GiB already allocated; 5.75 MiB free; 20.88 MiB cached)